variables:
  WindowsContainerImage: "cdpxwin1809.azurecr.io/global/obinfra/windows/1809/vs2019:latest"

# package_sources:
#   npm:
#     config_files:
#       - include:
#           - 'scripts\.npmrc'

steps:
  - task: onebranch.pipeline.version@1
    inputs:
      system: "RevisionCounter"
      major: "1"
      minor: "3"
      ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        tag: official

stages:
  - stage: build
    jobs:
      - job: cdpx_global
        pool:
          type: windows
        variables:
          ob_outputDirectory: '$(Build.SourcesDirectory)\output'
        steps:
          - task: CmdLine@2
            displayName: 'NPM Install'
            inputs:
              script: '$(Build.SourcesDirectory)\npmInstall.cmd'
              workingDirectory: '$(Build.SourcesDirectory)'
          
          - task: CmdLine@2
            displayName: 'NPM Install scripts'
            inputs:
              script: '$(Build.SourcesDirectory)\scripts\npmInstall.cmd'
              workingDirectory: '$(Build.SourcesDirectory)'
              
          - task: CmdLine@2
            displayName: 'Get Localized Repos'
            inputs:
              script: '$(Build.SourcesDirectory)\scripts\restoreDocs.cmd'
              workingDirectory: '$(Build.SourcesDirectory)'
          
          - task: CmdLine@2
            displayName: 'Restore Loc'
            inputs:
              script: '$(Build.SourcesDirectory)\scripts\restoreLoc.cmd'
              workingDirectory: '$(Build.SourcesDirectory)'